services:
  db:
    image: 'postgres:14-alpine'
    container_name: productsExam
    restart: always
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5433:5432"